version: '3.8'
services: #This section defines all the different containers we will create.
  gardentify-client: #This is the name of our Nextjs application.
    build: #This specifies the location of our Dockerfile
      context: . #This specifies the location of our Dockerfile
      dockerfile: Dockerfile
    ports: #This is used to map the container’s ports to the host machine.
      - 3000:3000
    expose:
      - 3000
    env_file:
      - .env
